### ISSUE TITLE
qdbus is not available on all distros

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-latte-sidebar-button#1]
https://github.com/psifidotos/applet-latte-sidebar-button/blob/3eaa327b5c72ea62ac7cc71c4d2f05d27c70d0e8/contents/ui/main.qml#L81

On my Tumbleweed setup, there is only `qdbus-q5`. Maybe we could use:
```bash
qdbus-qt5 blablah || qdbus blahblah
```

so if `qdbus-qt5` is not available, qdbus will be used.

**Comment by psifidotos** [comment]
But if there are both, it will be double executed...

**Comment by trmdi** [comment]
No, if the first command succeed, the second one will not run.

**Comment by psifidotos** [comment]
Strange, I am in Tumbleweed and qdbus works just fine

**Comment by Vogtinator** [comment]
`qdbus` is the Qt4 variant, which isn't even part of Tumbleweed anymore for some time.

It should either try `qdbus-qt5` and if it's not available use `qdbus`, or determine the location of Qt 5 binaries during build time, which for an applet isn't really possible...

**Comment by sowelipililimute** [comment]
> Strange, I am in Tumbleweed and qdbus works just fine

qdbus is the Qt4 version of qdbus. qdbus-qt5 is the Qt5 version of qdbus.

**Comment by Vogtinator** [comment]
There seems to be some demand for getting support for DBus calls in QML, I would say that it's the way forward instead of running an external command.

**Comment by psifidotos** [comment]
> There seems to be some demand for getting support for DBus calls in QML, I would say that it's the way forward instead of running an external command.

This applet will be qml only, do you know a qml way to make dbus calls that I am not aware of?

**Comment by Vogtinator** [comment]
Unfortunately not, only in kwin scripts: https://github.com/KDE/kwin/blob/861883895d2028c68bc5f1274f86af63dc6d1a7f/scripting/dbuscall.h#L29

**Comment by psifidotos** [comment]
So we can use @trmdi recommendation then or give the user a choice in the applet configuration window to write the external command to be used.

**Comment by trmdi** [comment]
I think an automatic way would be better.
And I guess these two commands would be enough in all cases.

```bash
qdbus-qt5 blahblah || qdbus blahblah || echo "Please install qdbus-qt5/qdbus..."
```

Or maybe `dbus-send` instead?
```bash
$ dbus-send --type=method_call --dest=org.kde.lattedock /Latte org.kde.LatteDock.toggleHiddenState string:"" string:"LVDS-1" int32:5
```
