### ISSUE TITLE
The fonts at the top of the applet do not look right. 

### ISSUE THREAD

**Issue by AuthFailed** [psifidotos/applet-latte-sidebar-button#12]
I have installed ttf-dejavu and ttf-liberation as well.
![image](https://user-images.githubusercontent.com/21986465/114270708-12409300-9a38-11eb-87ad-57b578cf65dc.png)

**Comment by psifidotos** [comment]
1. This is not applet responsibility
2. If you means the sidebar fonts, latte is not responsible for applets fonts.add a plasma panel with same applets and you will have same result.

**Comment by AuthFailed** [comment]
I added a notification applet, and the fonts look fine
![image](https://user-images.githubusercontent.com/21986465/114271094-e6bea800-9a39-11eb-91c2-a2fbb0c92bb2.png)

**Comment by psifidotos** [comment]
Where did you add notification applet? Both screenshots are showing notification applet.

And what is knopwob dunst service?

**Comment by psifidotos** [comment]
Btw the second screenshot is from plasma systray popup and not what I proposed you to do.

Add a plasma panel, increase its thickness to 256px.and then add notification applet in it, not in the systray.

In any way, the correct place to report this is at plasma bugs, plasmashell, Notifications
