### ISSUE TITLE
Applet doesn't work anymore

### ISSUE THREAD

**Issue by Octoton** [psifidotos/applet-latte-sidebar-button#15]
I just pull the latest change on master (commit: 21b187b94c835954cb6a55c769f32fee6652b6cb) and the applet doesn't open my left on demand sidebar anymore
Here is my config is that can help, as i don't know how to give you better information about the problem
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.4.116-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 15,4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by psifidotos** [comment]
You need to update in latest latte git version and 0.2 version for this applet
