### ISSUE TITLE
Button does not toggle side bar.

### ISSUE THREAD

**Issue by piyushmanolkar** [psifidotos/applet-latte-sidebar-button#2]
Arch Linux
Plasma 5

Latte Dock git version

![deepin-screen-recorder_Select area_20200413132333](https://user-images.githubusercontent.com/36564289/79103576-7d567b80-7d8a-11ea-910c-50efc7c188e8.gif)

Will attach more info if needed.

**Comment by psifidotos** [comment]
Show me a screenshot of your button settings and a screenshot of your Behavior advanced settings for your side panel

**Comment by piyushmanolkar** [comment]
It started working after I removed the sidebar, added and configured the button and then added the sidebar.
But it's still an issue if the sidebar is added first.

**Comment by piyushmanolkar** [comment]
It started working after I removed both button and the sidebar, added and configured the button and then added the sidebar. But doing this in the reverse order still is an issue.

**Comment by psifidotos** [comment]
You didn't send the screenshots

**Comment by piyushmanolkar** [comment]
![DeepinScreenshot_select-area_20200415135926](https://user-images.githubusercontent.com/36564289/79316127-87f74900-7f21-11ea-90b9-0172c5eb3148.png)
![DeepinScreenshot_select-area_20200415140009](https://user-images.githubusercontent.com/36564289/79316137-8af23980-7f21-11ea-946c-79a3ab1a29a3.png)

**Comment by psifidotos** [comment]
Ok... tracked down to Latte... Please try to again with latest Latte git version, it should be fixed

**Comment by ademcal** [comment]
it have same problem me to, my system is Manjaro-KDE X64 I clicked icon but nothing I dont know why I am using latte-dock-git version
Buy the way I tryed this command `plasmapkg2 -i .` in the / local/share.... app folder it says succesfull installed 
beside in this git version, system widget explorer, aur git version unfortunately same problem shortly dont work your applet....

**Comment by psifidotos** [comment]
It works just fine. Something is wrong in your system

**Comment by ademcal** [comment]
for example ... it can be ??

**Comment by psifidotos** [comment]
Latest latte git version, latest applet version and relogin.

I can't help you any further you need to ask for help to forums and your distro.

**Comment by Aleksanaa** [comment]
> Latest latte git version, latest applet version and relogin.
> 
> I can't help you any further you need to ask for help to forums and your distro.

After doing them,the problem still exists.
Archlinux latest.
