### ISSUE TITLE
"org.kde.latte" is not installed

### ISSUE THREAD

**Issue by xbjfk** [psifidotos/applet-latte-sidebar-button#3]
Hello, when I attempt to click the sidebar button, I get a popup that says this:
```
Error loading QML file: file:///home/trainz-are-kul/.local/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/main.qml:27:1: module "org.kde.latte" is not installed
```
I am on the latest version of latte-sidebar-button (from Discover) and latte git version (just updated 2 mins ago)
I have also tried clear-cache

Thanks in advance :smile:

**Comment by psifidotos** [comment]
the latte-sidebar-button version you are using is not the latest. Try the following

1. Remove the latte sidebar button from Discover
2. Plasma Widget Explorer -> Get New Widgets -> Download New Plasma Widgets -> Installed
2.1 Remove Latte Sidebar button if it still appears in installed widgets list
3. After [1],[2] reinstall the applet from any way you prefer and relogin to your Plasma
