### ISSUE TITLE
QML Load Error

### ISSUE THREAD

**Issue by Reverier-Xu** [psifidotos/applet-latte-sidebar-button#4]
```
File upload error QML: file:///usr/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/main.qml:97:5: Type Icons.GeneralIcon unavailable
file:///usr/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/icons/GeneralIcon.qml:43:9: Type LatteIcon unavailable
file:///usr/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/icons/LatteIcon.qml:22:1: module "org.kde.latte.core" is not installed
```
I found the description in KDE Store, it said the latte dock version must be >= 0.10,

but

![Screenshot_20200516_012611](https://user-images.githubusercontent.com/41937333/82078761-41f5f680-9714-11ea-92d4-b3e3086b2072.png)

The latest version is 0.9.11 ......

**Comment by psifidotos** [comment]
it means that you need to use at least Latte Git version which is under current development...
