### ISSUE TITLE
load QML file error

### ISSUE THREAD

**Issue by Hoking007** [psifidotos/applet-latte-sidebar-button#5]
装入 QML 文件出错：file:///home/hoking/.local/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/main.qml:97:5: Type Icons.GeneralIcon unavailable
file:///home/hoking/.local/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/icons/GeneralIcon.qml:43:9: Type LatteIcon unavailable
file:///home/hoking/.local/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/icons/LatteIcon.qml:22:1: module "org.kde.latte.core" is not installed

**Comment by psifidotos** [comment]
Update to latest Latte git version
