### ISSUE TITLE
error when clicking in it

### ISSUE THREAD

**Issue by marcelo-fm** [psifidotos/applet-latte-sidebar-button#6]
hi, i'm having this error when i click in it:

Ocorreu um erro ao carregar o arquivo QML: 

> file:///home/marcelo/.local/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/main.qml:97:5: Type Icons.GeneralIcon unavailable
> file:///home/marcelo/.local/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/icons/GeneralIcon.qml:43:9: Type LatteIcon unavailable
> file:///home/marcelo/.local/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/icons/LatteIcon.qml:22:1: module "org.kde.latte.core" is not installed

i don't know if i am doing something wrong, but anyway here is the error. thanks in advance

**Comment by psifidotos** [comment]
You need to update Latte at latest git version

**Comment by tonyvfish** [comment]
Is there an earlier version of this, that does not require a dev build of latte please, I don't want to install a dev build
