### ISSUE TITLE
Latte SideBar won't launch

### ISSUE THREAD

**Issue by YamiYukiSenpai** [psifidotos/applet-latte-sidebar-button#7]
This is what showed up on the notifications:
```
Error loading QML file: file:///home/yamiyukisenpai/.local/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/main.qml:97:5: Type Icons.GeneralIcon unavailable
file:///home/yamiyukisenpai/.local/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/icons/GeneralIcon.qml:43:9: Type LatteIcon unavailable
file:///home/yamiyukisenpai/.local/share/plasma/plasmoids/org.kde.latte.sidebarbutton/contents/ui/icons/LatteIcon.qml:22:1: module "org.kde.latte.core" is not installed
```
The Latte Dock version is 0.9.11+p20.04+git20200624.1033-0 from KDE Neon's repo.

System info:
Operating System: KDE neon Testing Edition
KDE Plasma Version: 5.19.3
KDE Frameworks Version: 5.73.0
Qt Version: 5.14.2
Kernel Version: 5.4.0-7634-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-6500 CPU @ 3.20GHz
Memory: 15.6 GiB of RAM
Graphics Processor: GeForce GTX 1060 6GB/PCIe/SSE2

**Comment by psifidotos** [comment]
You need Latte git version, not 0.9.11

**Comment by YamiYukiSenpai** [comment]
> You need Latte git version, not 0.9.11

oh!  My bad.  Why isn't it officially released yet?
