### ISSUE TITLE
WIdgets outside sidebar ?

### ISSUE THREAD

**Issue by jazbina** [psifidotos/applet-latte-sidebar-button#9]
Hi,

first, congrats on great work you have done ! 

But, I have problem with sidebar.
There is no media player or notification inside sidebar, there are icons instead.
When I click on them I can see player and notifications outside of sidebar.
Widgets stay on desktop when I close sidebar and go away when I click on desktop. 
Controls and everything else is working fine.

I am on openSUSE Tumbleweed and  lattedock 999.git.20210107.33ad9069

![latte-sidebar](https://user-images.githubusercontent.com/1221082/104060120-becf6680-51f6-11eb-9c0f-94f30788e8a4.png)

**Comment by psifidotos** [comment]
https://userbase.kde.org/LatteDock/FAQ#How_can_I_set_the_maximum_icon_size_for_applets_in_Plasma_panels.3F

**Comment by marcinpan** [comment]
despite changing to 192 pixels, icons are still displayed as above

**Comment by psifidotos** [comment]
> despite changing to 192 pixels, icons are still displayed as above

that is applets problem then

**Comment by marcinpan** [comment]
Is there any solution to this problem?
The icons have increased, but notifications appear only after clicking as above

**Comment by psifidotos** [comment]
> Is there any solution to this problem? The icons have increased, but notifications appear only after clicking as above

no... the applets need to improve their implementation

**Comment by marcinpan** [comment]
Thanks for the clarification.
It is a pity that it does not work: /

**Comment by jazbina** [comment]
> Is there any solution to this problem? The icons have increased, but notifications appear only after clicking as above

Try changing to more than 192 pixels.  I am using 430 pixels. 
Right click on the panel than choose Edit panel > Appearance > Items > Absolute size

**Comment by marcinpan** [comment]
It does not change anything, I was set to even 450 pixels.
But thanks for the advice
